#!/bin/bash
#
# A pre-commit hook to automatically generate requirements files
# from the install_requires and extra_requires entries in the
# setup.cfg file.
# These are only present to allow github's dependabot tool to actually
# monitor our packages

# Redirect output to stderr.
exec 1>&2

pythonAliases=("python3" "py" "python")
hasPython=0

for alias in "${pythonAliases[@]}"; do
  if command -v "$alias"; then
    pythonAlias="$alias"
    hasPython=1
    break
  fi
done

if [ -z "$hasPython"  ]; then
  echo "No python was detected, ensure it is available on your path as one of:"
  echo "${pythonAliases[*]}"
  exit 1
fi

ROOT_DIR=$(git rev-parse --show-toplevel)
pushd "$ROOT_DIR/requires" || exit 1
"$pythonAlias" ./generate_requirements.py
if test -f "./.updated"; then
	rm ./.updated
	git add ./*_requirements.txt
fi
popd || exit 0