# Copyright (C) 2022 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from ansys.openapi.common import ModelBase, Unset


class ExampleException(ModelBase):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "exception_text": "str",
        "exception_code": "ExampleIntEnum",
        "stack_trace": "list[str]",
    }

    attribute_map = {
        "exception_text": "ExceptionText",
        "exception_code": "ExceptionCode",
        "stack_trace": "StackTrace",
    }

    subtype_mapping = {}

    def __init__(
        self,
        exception_text=Unset,
        exception_code=Unset,
        stack_trace=Unset,
    ):  # noqa: E501
        self._exception_text = (None,)
        self._exception_code = (None,)
        self._stack_trace = (None,)
        self.discriminator = None
        if exception_text is not None:
            self._exception_text = exception_text
        if exception_code is not None:
            self._exception_code = exception_code
        if stack_trace is not None:
            self._stack_trace = stack_trace

    @property
    def exception_text(self):
        return self._exception_text

    @exception_text.setter
    def exception_text(self, exception_text):
        self._exception_text = exception_text

    @property
    def exception_code(self):
        return self._exception_code

    @exception_code.setter
    def exception_code(self, exception_code):
        self._exception_code = exception_code

    @property
    def stack_trace(self):
        return self._stack_trace

    @stack_trace.setter
    def stack_trace(self, stack_trace):
        self._stack_trace = stack_trace

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
