# Copyright (C) 2022 - 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# PEP 563: postpone evaluating annotations. Required here because
# ``OIDCSessionFactory`` is only defined when the optional OIDC extra imports
# succeed. Unions like ``OIDCSessionFactory | None`` must not execute at module
# import in bare environments.
# Remove this import when ``requires-python`` is high enough that annotations are
# evaluated lazily by default (monitor PEP 649 / CPython release notes), or when
# this module no longer cites possibly-undefined names (e.g. use only string hints
# such as ``"OIDCSessionFactory | None"``).
from __future__ import annotations

from enum import Enum
import os
from typing import TYPE_CHECKING, Literal, TypeVar
from urllib.parse import urlparse, urlunparse
import warnings

import httpx
from httpx import BasicAuth

from . import __version__
from ._api_client import ApiClient
from ._exceptions import ApiConnectionException, AuthenticationWarning
from ._logger import logger
from ._util import (
    CaseInsensitiveOrderedDict,
    SessionConfiguration,
    collect_www_authenticate_raw_values,
    create_httpx_client_from_session_configuration,
    generate_user_agent,
    parse_authenticate,
)

if TYPE_CHECKING:
    from ._util import CaseInsensitiveOrderedDict

_oidc_enabled = True
_linux_kerberos_enabled = True
_platform_windows = False

try:
    # noinspection PyUnresolvedReferences
    import keyring
    import httpx_auth  # noqa: F401

    from ._oidc import OIDCSessionFactory
except ImportError:
    _oidc_enabled = False

if os.name == "nt":
    _platform_windows = True
else:
    try:
        import httpx_gssapi  # noqa: F401

        _linux_kerberos_enabled = True
    except ImportError:
        _linux_kerberos_enabled = False

    _platform_windows = False

# Required to allow the ApiClientFactory to be subclassed. This ensures that Pylance
# understands that the subclass is returned by the builder methods instead of the base class
Api_Client_Factory = TypeVar("Api_Client_Factory", bound="ApiClientFactory")


class AuthenticationScheme(Enum):
    """Authentication scheme.

    Used to specify an authentication scheme used when connecting to the server with credentials.

    .. only:: OpenapiCommonStandaloneBuild

        .. versionadded:: 2.1

    .. only:: not OpenapiCommonStandaloneBuild

        .. tip::
           Added as :class:`~ansys.openapi.common.AuthenticationScheme` in version 2.1 of
           ``ansys-openapi-common``.
    """

    AUTO = "auto"
    """Use the 401 response WWW-Authenticate header to select the best supported authentication scheme."""

    BASIC = "Basic"
    """Force the use of Basic authentication, even if more secure options are supported."""

    NTLM = "NTLM"
    """Force the use of NTLM authentication only. Do not fall back to Basic authentication."""


class ApiClientFactory:
    """Creates a factory that configures an API client for use with autogenerated Swagger clients.

    This method handles setup of the retry strategy, session-level timeout, and any additional
    configuration for the HTTP client. Authentication must be configured afterwards using one of
    the other class methods.

    Call :meth:`close` when the factory (or any :class:`ApiClient` from :meth:`connect`) is no
    longer needed, so the underlying HTTP client releases connections.

    Parameters
    ----------
    api_url : str
       Base URL of the API server.
    session_configuration : ~ansys.openapi.common.SessionConfiguration, optional
       Additional configuration settings for the HTTP client.
    """

    _session: httpx.Client
    _api_url: str
    _auth_header: "CaseInsensitiveOrderedDict"
    _configured: bool

    def __init__(
        self, api_url: str, session_configuration: SessionConfiguration | None = None
    ) -> None:
        self._api_url = api_url
        self._configured = False
        logger.info(f"Creating new session at '{api_url}")

        if session_configuration is None:
            session_configuration = SessionConfiguration()

        if "User-Agent" not in session_configuration.headers:
            user_agent = generate_user_agent("ansys-openapi-common", __version__)
            session_configuration.headers["User-Agent"] = user_agent
        self._session_configuration = session_configuration

        self._session = create_httpx_client_from_session_configuration(
            session_configuration,
            mount_scheme_url=api_url,
        )

        logger.debug(
            f"Configured httpx client default timeout "
            f"with value '{self._session_configuration.request_timeout}'"
        )
        logger.debug(
            "Retry policy: RetryingHTTPTransport "
            f"(max_attempts={self._session_configuration.retry_count})."
        )

        logger.info("Base session created.")

    @staticmethod
    def _root_probe_url(api_url: str) -> str:
        """Normalize URL for the initial ``GET`` probe against the API.

        Bare ``scheme://host[:port]`` URLs omit the path segment that maps to the ASGI ``"/"``
        route in typical FastAPI apps; normalize those to ``scheme://host[:port]/``.

        If ``api_url`` already contains a non-root path (for example ``http://host/service``),
        that path is preserved without forcing an extra trailing slash.
        """
        p = urlparse(api_url)
        if p.path in ("", "/"):
            normalized_path = "/"
        else:
            normalized_path = p.path.rstrip("/") or "/"
        return urlunparse((p.scheme, p.netloc, normalized_path, p.params, p.query, p.fragment))

    def _validate_builder(self) -> None:
        if not self._configured:
            raise ValueError("No authentication configured yet.")

    def connect(self) -> ApiClient:
        """Finalize the API client and return it for use.

        Authentication must be configured for this method to succeed.

        Returns
        -------
        ~ansys.openapi.common.ApiClient
            Client object that can be used to connect to the server and perform API operations.

        Raises
        ------
        ValueError
            When the client is not fully configured.
        """
        self._validate_builder()
        return ApiClient(self._session, self._api_url, self._session_configuration)

    def close(self) -> None:
        """Close the underlying HTTP client and release pooled connections."""
        self._session.close()

    def with_anonymous(self: Api_Client_Factory) -> Api_Client_Factory:
        """Set up client authentication for anonymous use.

        This does not configure any authentication or authorization headers. Users must provide any
        authentication information required themselves.

        Clients relying on custom authentication such as client certificates or non-standard tokens
        should use this method.

        Returns
        -------
        ~ansys.openapi.common.ApiClientFactory
            Original client factory object.
        """
        self.__test_connection()
        logger.info("Connection successful.")
        self._configured = True
        return self

    def with_credentials(
        self: Api_Client_Factory,
        username: str,
        password: str,
        domain: str | None = None,
        authentication_scheme: AuthenticationScheme = AuthenticationScheme.AUTO,
    ) -> Api_Client_Factory:
        """Set up client authentication for use with provided credentials.

        The default operation of this method is to attempt to connect to the API and to use the provided
        ``WWW-Authenticate`` header to determine whether NTLM or Basic Authentication should be used. The selected
        authentication scheme will then be configured for use.

        Parameters
        ----------
        username : str
            Username for the connection.
        password : str
            Password for the connection.
        domain : str, optional
            Domain to use for connection if required. The default is ``None``.
        authentication_scheme : ~ansys.openapi.common.AuthenticationScheme
            The authentication scheme to use.

            .. only:: OpenapiCommonStandaloneBuild

                .. versionadded:: 2.1

            .. only:: not OpenapiCommonStandaloneBuild

                .. tip::
                   Added to
                   :meth:`ApiClientFactory.with_credentials <ansys.openapi.common.ApiClientFactory.with_credentials>`
                   in version 2.1 of ``ansys-openapi-common``.

        Returns
        -------
        ~ansys.openapi.common.ApiClientFactory
            Original client factory object.

        Raises
        ------
        ConnectionError
            If the server does not support Basic or NTLM authentication (Windows clients only).

        Notes
        -----
        NTLM authentication is not currently supported on Linux.
        """
        if authentication_scheme == AuthenticationScheme.NTLM and not _platform_windows:
            raise ValueError("AuthenticationScheme.NTLM is not supported on Linux.")

        logger.info(f"Setting credentials for user '{username}'.")
        if domain is not None:
            username = f"{domain}\\{username}"
            logger.debug(f"Setting domain for username, connecting as '{username}'.")

        if authentication_scheme == AuthenticationScheme.AUTO:
            initial_response = self._session.get(ApiClientFactory._root_probe_url(self._api_url))
            if self.__handle_initial_response(initial_response):
                return self
            headers = self.__get_authenticate_header(initial_response)
            logger.debug(
                "Detected authentication methods: "
                + ", ".join([method for method in headers.keys()])
            )
        else:
            headers = CaseInsensitiveOrderedDict()

        if (
            "Negotiate" in headers
            or "NTLM" in headers
            or authentication_scheme == AuthenticationScheme.NTLM
        ):
            if _platform_windows:
                logger.debug("Attempting to connect with NTLM authentication...")
                from httpx_ntlm import HttpNtlmAuth

                self._session.auth = HttpNtlmAuth(username, password)
                self.__test_connection()
                logger.info("Connection successful.")
                self._configured = True
                return self
        if "Basic" in headers or authentication_scheme == AuthenticationScheme.BASIC:
            logger.debug("Attempting connection with Basic authentication...")
            self._session.auth = BasicAuth(username, password)
            self.__test_connection()
            logger.info("Connection successful.")
            self._configured = True
            return self
        raise ConnectionError("Unable to connect with credentials provided.")

    def with_autologon(self: Api_Client_Factory) -> Api_Client_Factory:
        """Set up client authentication for use with Kerberos (also known as integrated Windows authentication).

        The default operation of this method is to attempt to connect to the API and to use the provided
        ``WWW-Authenticate`` header to determine if Negotiate authentication is supported by the server. If so,
        Negotiate will then be used for authentication.

        If Negotiate authentication is not supported by the server, an exception is raised.

        Returns
        -------
        ~ansys.openapi.common.ApiClientFactory
            Current client factory object.

        Raises
        ------
        ConnectionError
            If the server does not support Negotiate authentication.

        Notes
        -----
        Requires the user to have a valid Kerberos Ticket-Granting-Ticket (TGT).

        * On Windows, this is provided by default.
        * On Linux, this requires the ``[linux-kerberos]`` extension to be installed and your Kerberos installation
          to be configured correctly.
        """
        if not (_platform_windows or _linux_kerberos_enabled):
            raise ImportError(
                "Kerberos is not enabled. To use it, run `pip install ansys-openapi-common[linux-kerberos]`."
            )
        initial_response = self._session.get(ApiClientFactory._root_probe_url(self._api_url))
        if self.__handle_initial_response(initial_response):
            return self
        headers = self.__get_authenticate_header(initial_response)
        logger.debug(
            "Detected authentication methods: " + ", ".join([method for method in headers.keys()])
        )
        if "Negotiate" in headers:
            logger.debug("Attempting connection with Negotiate authentication...")
            if _platform_windows:
                from httpx_negotiate_sspi import HttpSspiAuth

                logger.debug(f"Using {HttpSspiAuth.__qualname__} as a Negotiate backend.")
                self._session.auth = HttpSspiAuth()
            else:
                from httpx_gssapi import HTTPSPNEGOAuth

                logger.debug(f"Using {HTTPSPNEGOAuth.__qualname__} as a Negotiate backend.")
                self._session.auth = HTTPSPNEGOAuth()
            self.__test_connection()
            logger.info("Connection successful.")
            self._configured = True
            return self
        raise ConnectionError("Unable to connect with autologon.")

    def with_oidc(
        self,
        idp_session_configuration: SessionConfiguration | None = None,
    ) -> "OIDCSessionBuilder":
        """Set up client authentication for use with OpenID Connect.

        Parameters
        ----------
        idp_session_configuration : ~ansys.openapi.common.SessionConfiguration, optional
            Additional configuration settings for the HTTP client when connected to the OpenID identity provider.
            The initial anonymous probe of the **API** uses only the factory's ``session_configuration`` (see
            ``ApiClientFactory`` constructor); put resource-server headers such as application identity there.

        Returns
        -------
        ~ansys.openapi.common.OIDCSessionBuilder
            Builder object to authenticate via OIDC.

        Notes
        -----
        OIDC Authentication requires the ``[oidc]`` extra to be installed.
        """
        if not _oidc_enabled:
            raise ImportError(
                "OpenID Connect features are not enabled. To use them, run `pip install ansys-openapi-common[oidc]`."
            )
        initial_response = self._session.get(ApiClientFactory._root_probe_url(self._api_url))
        if self.__handle_initial_response(initial_response):
            return OIDCSessionBuilder(self)

        session_factory = OIDCSessionFactory(
            initial_response,
            self._session_configuration,
            idp_session_configuration,
        )

        return OIDCSessionBuilder(self, session_factory)

    def __test_connection(self) -> Literal[True]:
        """Attempt to connect to the API server.

        If the server returns a 2XX status code, the method returns ``True``. Otherwise, the method will
        throw an :obj:`APIConnectionError` object with the status code and the reason phrase. If the
        underlying HTTP client raises an exception of its own, it is left to propagate as-is
        (for example, an SSL error if the remote certificate is untrusted).

        Returns
        -------
        Literal[True]
            If the test is successful.

        Raises
        ------
        APIConnectionError
            If the API server returns a status code other than 2XX.
        """
        resp = self._session.get(ApiClientFactory._root_probe_url(self._api_url))
        if 200 <= resp.status_code < 300:
            return True
        else:
            raise ApiConnectionException(resp)

    def __handle_initial_response(
        self, initial_response: httpx.Response
    ) -> ApiClientFactory | None:
        """Verify that an initial 401 response is returned if we expect to require authentication.

        If a 2XX response is returned, then all is well, but we will not use any authentication in
        future. Otherwise, something else has gone awry: return an :obj:`ApiConnectionException`
        object with information about the response.

        Parameters
        ----------
        initial_response : httpx.Response
            Response from querying the API server.

        Raises
        ------
        ApiConnectionError
            If the API server returns a status code other than 2XX or 401.

        Warns
        -----
        AuthenticationWarning
            If the connection succeeds when the user's requested authentication suggests it should fail.
        """
        if 200 <= initial_response.status_code < 300:
            warnings.warn(
                AuthenticationWarning(
                    "Credentials were provided but server accepts anonymous "
                    "connections. Continuing without credentials."
                )
            )
            logger.info("Connection successful.")
            self._configured = True
            return self
        elif initial_response.status_code != 401:
            raise ApiConnectionException(initial_response)
        else:
            return None

    @staticmethod
    def __get_authenticate_header(
        response: httpx.Response,
    ) -> "CaseInsensitiveOrderedDict":
        """Extract the ``WWW-Authenticate`` header from an HTTP response.

        Parameters
        ----------
        response : httpx.Response
            Raw response from the API server.

        Raises
        ------
        ValueError
            If the response contains no ``WWW-Authenticate`` header to be parsed.
        """
        raw_values = collect_www_authenticate_raw_values(response)
        if not raw_values:
            raise ValueError("No www-authenticate header was provided. Cannot continue...")
        merged = CaseInsensitiveOrderedDict()
        for chunk in raw_values:
            merged.update(parse_authenticate(chunk))
        return merged


class OIDCSessionBuilder:
    """Helps create OpenID Connect sessions and provides OIDC-specific configuration options.

    Parameters
    ----------
    client_factory : ~ansys.openapi.common.ApiClientFactory
        Parent API client factory object that will be returned once configuration is complete.
    session_factory : ~ansys.openapi.common.OIDCSessionFactory, optional
        OIDC session factory object that will be configured and used to return an OAuth-supporting session.
    """

    def __init__(
        self,
        client_factory: ApiClientFactory,
        session_factory: OIDCSessionFactory | None = None,
    ) -> None:
        self._client_factory = client_factory
        self._session_factory = session_factory

    def with_stored_token(self, token_name: str = "ansys-openapi-common-oidc") -> ApiClientFactory:
        """Use a token stored in the system keyring to authenticate the session.

        This method requires a correctly configured system keyring backend.

        Parameters
        ----------
        token_name : str
            Name of the token key in the system keyring.

        Returns
        -------
        ~ansys.openapi.common.ApiClientFactory
           Original client factory object.

        Raises
        ------
        ValueError
            If no token is found in the system keyring with the provided ``token_name``.
        """
        if self._session_factory is None:
            return self._client_factory
        refresh_token = keyring.get_password(token_name, self._client_factory._api_url)
        if refresh_token is None:
            raise ValueError("No stored credentials found.")

        return self.with_token(refresh_token=refresh_token)

    def with_access_token(self, access_token: str) -> ApiClientFactory:
        """Use a provided access token to authenticate the session.

        This method configures a session with the provided access token, if the token is invalid,
        or has expired, the session will be unable to authenticate.

        Parameters
        ----------
        access_token : str
            Access token.

        Returns
        -------
        ~ansys.openapi.common.ApiClientFactory
            Original client factory object.

        .. versionadded:: 2.2.3
        """
        if self._session_factory is None:
            return self._client_factory
        self._client_factory._session = self._session_factory.get_session_with_access_token(
            access_token=access_token
        )
        self._client_factory._configured = True
        return self._client_factory

    def with_refresh_token(self, refresh_token: str) -> ApiClientFactory:
        """Use a provided refresh token to authenticate the session.

        The refresh token will be used to request a new access token from the Identity Provider,
        this will be automatically refreshed shortly before expiration.

        Parameters
        ----------
        refresh_token : str
            Refresh token.

        Returns
        -------
        ~ansys.openapi.common.ApiClientFactory
            Original client factory object.

        .. versionadded:: 2.2.3
        """
        if self._session_factory is None:
            return self._client_factory
        self._client_factory._session = self._session_factory.get_session_with_provided_token(
            refresh_token=refresh_token
        )
        self._client_factory._configured = True
        return self._client_factory

    def with_token(self, refresh_token: str) -> ApiClientFactory:
        """Use a provided refresh token to authenticate the session.

        The refresh token will be used to request a new access token from the Identity Provider,
        this will be automatically refreshed shortly before expiration.

        Parameters
        ----------
        refresh_token : str
            Refresh token.

        Returns
        -------
        ~ansys.openapi.common.ApiClientFactory
            Original client factory object.

        Notes
        -----
        The signature of this method will change in an upcoming release to allow both access and refresh
        tokens to be provided. Update usages to provide the ``refresh_token`` keyword argument rather than
        passing a positional argument.
        """
        return self.with_refresh_token(refresh_token=refresh_token)

    def authorize(self, login_timeout: int = 60) -> ApiClientFactory:
        """Authenticate the user interactively by opening a web browser and waiting for the user to log in.

        Parameters
        ----------
        login_timeout : int
            Time in seconds to wait for the user's web browser to authenticate. The default is ``60s``.

        Returns
        -------
        ~ansys.openapi.common.ApiClientFactory
            Original client factory object.
        """
        if self._session_factory is None:
            return self._client_factory
        self._client_factory._session = (
            self._session_factory.get_session_with_interactive_authorization(login_timeout)
        )
        self._client_factory._configured = True
        return self._client_factory
