name: Measure and Report Test Coverage

# run only on main branch.  This avoids duplicated actions on PRs
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Measure and upload test coverage
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      kdc-server:
        # Github container registry address
        image: ghcr.io/pyansys/kdc-container:v0.2
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        volumes:
          # This is needed otherwise there won't be enough entropy to generate a new kerberos realm
          - /dev/urandom:/dev/random
          - /tmp/keytabs:/tmp/keytabs
        ports:
          - 749:749
          - 88:88/udp

    container:
      image: python:3.10-buster
      volumes:
        - /tmp/keytabs:/tmp/keytabs
    steps:
      - uses: actions/checkout@v1

      - name: Configure host kerberos
        run: |
          apt update
          export DEBIAN_FRONTEND=noninteractive
          apt install -yq krb5-user
          cp ./tests/integration/krb5.conf /etc/krb5.conf
          ./tests/integration/configure_keytab.sh

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Test with tox
        run: tox -e coverage -- --kerberos

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
